spring:
  application:
    name: user-service

  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-seconds: ${APP_JWT_EXPIRATION_SECONDS:3600}
    issuer: ${APP_JWT_ISSUER:elibrary-user-service}
